
CREATE TABLE NOTICE (
    ID VARCHAR2(50),
    TITLE VARCHAR2(50),
    WRITER_ID VARCHAR2(50),
    CONTENT VARCHAR2(50),
    REGDATE TIMESTAMP,
    HIT NUMBER ,
    FILES VARCHAR2(50),
    PUB NUMBER(1,0)
)
DESC NOTICE;
SELECT * FROM NOTICE;
DROP TABLE NOTICE;

INSERT INTO NOTICE VALUES(ID.NEXTVAL,'JDBC란 무엇인가','newlec','aaa',SYSDATE,20,'',0);
INSERT INTO NOTICE VALUES(ID.NEXTVAL,'자바란 무엇인가','java','bbb',SYSDATE,5,'',1);
INSERT INTO NOTICE VALUES(ID.NEXTVAL,'오라클이란 무엇인가','lec','ccc',SYSDATE,15,'',2);
INSERT INTO NOTICE VALUES(ID.NEXTVAL,'스프링이란 무엇인가','fo','ddd',SYSDATE,23,'',3);
INSERT INTO NOTICE VALUES(ID.NEXTVAL,'C언어란 무엇인가','BBB','eee',SYSDATE,38,'',4);
INSERT INTO NOTICE VALUES(ID.NEXTVAL,'파이썬이란 무엇인가','lec','fff',SYSDATE,40,'',5);
INSERT INTO NOTICE VALUES(256,'newlec','hahaha','ff',SYSDATE,0,'',5);
SELECT * FROM NOTICE ORDER BY ID DESC; -- 내림차순 
SELECT NOTICE_SEQ.NEXTVAL FROM DUAL; -- 현재 시퀀스의 값 검색 
DROP SEQUENCE NOTICE_SEQ;
SELECT SEQUENCE_NAME FROM USER_SEQUENCES ;

INSERT INTO NOTICE (
    id,
    title,
    writer_id,
    content,
    regdate,
    hit,
    files,
    pub
) VALUES(
   SEQUENCE1.NEXTVAL,
   'JDBC란 무엇인가',
   'newlec',
   'aaa',
   SYSDATE,
   20,
   '',
   0
);
COMMIT; -- 무조건 커밋하자 ! 
SELECT * FROM MEMBER;
UPDATE NOTICE
SET
    TITLE='TEST3',
    CONTENT='HAHAHA',
    FILES=''  
WHERE ID = 12;

ROLLBACK; -- 원래되로 돌려놓음 

COMMIT;

SELECT * FROM NOTICE;